services:
    mongo-database:
      image: mongo:7.0.0
      container_name: mongo-database
      ports:
      - "4002:27017"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
   
    primes-database:
      image: postgres:alpine
      ports:
         - "4003:5432"
      environment:
         POSTGRES_PASSWORD: password
         POSTGRES_DB: primes

    prime-service:
      image: prime-service
      build:
        context: ../prime-service
        dockerfile: Dockerfile
      container_name: prime-service
      ports:
        - "4000:3000"
      environment:
        - server.port=3000
        - spring.datasource.url=jdbc:postgresql://primes-database:5432/primes
        - spring.datasource.username=postgres
        - spring.datasource.password=password
        - spring.datasource.restart=no

    arithm-service: 
      image: arithmetic-service
      build: 
        context: ../arithm-service
        dockerfile: Dockerfile 
      container_name: arithmetic-service
      ports:
        - "4005:3001"
      environment:
        - PORT=3001
      restart: "no"

#azure s